/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/9/23, 7:38 PM' 
 * Generated by 'banda' 
 * Generated on server 'SAI_DEEPIKA.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:50164/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257B88B232EF-9B07-4AA4-9BB3-85910EC3C9C4%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.FORECASTING_FINALPROJECT out=Work.preProcessedData;
	by Date;
run;

proc arima data=Work.preProcessedData plots
    (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecastonly));
	identify var=SpecificHumidity;
	estimate p=(1 2) (12) q=(1) (12) method=ML;
	identify var=log_Precipitation crosscorr=(SpecificHumidity);
	estimate p=(1 2) q=(1) input=(SpecificHumidity) method=ML;
	forecast lead=12 back=0 alpha=0.05 id=Date interval=month;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;